platform :ios, '8.0'
target 'CumulativeMicro' do
pod 'Masonry', '~>1.0.2'
pod 'ReactiveCocoa', '~>2.5'
pod 'MBProgressHUD', '~>1.0.0'
pod 'Toast', '~>3.1.0'
pod 'MMDrawerController', '~>0.6.0'
pod 'RESideMenu', '~>4.0.7'
pod 'YYModel', '~>1.0.4'
end
